Repository chipsalliance/tac, pull requests merged in 2021-05, with the labels that each got.

#32 Add Surelog / UHDM sandbox applicaton
  projects/sandbox/surelog_and_uhdm.md
Labels: sandbox-application

#29 OpenFASOC application
  projects/sandbox/OpenFASOC.md
Labels: sandbox-application

#36 Update project list
  README.md
Labels: fast-track

#40 Clarify language around project applications
  projects/PROJECT_APPLICATION_TEMPLATE.md
Labels: fast-track

#41 Application for Verible
  projects/graduated/verible.md
Labels: graduated-application, vote-passed

#42 Surelog-UHDM graduation form
  projects/graduated/surelog_and_uhdm.md
Labels: graduated-application, vote-required

#43 Add Henner Zeller to TSC
  README.md
Labels: fast-track

#44 Add process for immediately merging trivial PRs
  README.md
Labels: fast-track

#50 Rework Sandbox Section
  README.md
Labels: editorial

#52 Simplify Sandbox dir README so that it requires no maintenance
  projects/sandbox/README.md
Labels: editorial

#53 Simplify graduated readme
  projects/graduated/README.md
Labels: editorial
