Repository chipsalliance/tac, pull requests merged in 2021-06, with the labels that each got.

#59 Remove project list from the Archived projects README
  projects/archived/README.md
Labels: editorial

#55 Remove UHDM/Surelog from Sandbox, as it's already Graduated
  projects/sandbox/surelog_and_uhdm.md
Labels: fast-track

#54 Refactor the main README
  README.md
Labels: fast-track

#45 Add May 2021 TSC minutes + June agenda proposal
  meetings/2021-05-26.md
  meetings/2021-06-24.md
Labels: fast-track

#63 Editorial fixes to OpenFASOC application
  projects/graduated/OpenFASOC.md
Labels: editorial

#64 Add M. Saligane to TSC composition
  README.md
Labels: editorial

#65 Remove OpenFASOC from Sandbox
  projects/sandbox/OpenFASOC.md
Labels: editorial

#67 Remove the intro in AIB sandbox application
  projects/sandbox/aib.md
Labels: editorial

#68 Remove OmniXtend Sandbox application intro and outro
  projects/sandbox/omnixtend.md
Labels: editorial

#38 Propose espresso to Sandbox projects
  projects/sandbox/espresso.md
Labels: needs-investigation, tsc-meeting
